--- # Get ASG details
- hosts: localhost
  module_defaults:
    group/aws:
     
      region: ap-south-1

  tasks:
      - ec2_group_info: 
        register: asgs

      - name: print asg
        debug: var=asgs
